'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const S = require('./hitster-star-ledger.js');
const teams = [{id:'one'},{id:'two'}];
test('ten distinct types, separate from quantities',()=>assert.deepEqual(S.rules.map(r=>r.id),[1,2,3,4,5,6,7,8,9,10]));
test('latest star nine interpretation is 999, not 50000',()=>assert.equal(S.ruleFor(9).value,999));
test('explicit anchors remain unchanged',()=>assert.deepEqual([1,2,3,5].map(id=>S.ruleFor(id).value),[10,20,50,500]));
test('unapproved proposals stay inactive',()=>assert.deepEqual([4,6,7,8,10].map(id=>S.ruleFor(id).value),[null,null,null,null,null]));
test('two stars of type nine total 1998',()=>assert.equal(S.total({9:2}),1998));
test('mixed type quantities use their own values',()=>assert.equal(S.total({1:1,2:2,3:3,5:1,9:2}),2698));
test('an empty ledger is zero, not an invented award',()=>assert.equal(S.total({}),0));
test('rejects an unapproved type with quantity',()=>assert.throws(()=>S.total({4:1}),RangeError));
test('rejects negative, fractional, infinite and string quantities',()=>{for(const q of [-1,0.5,NaN,Infinity,'2',1000001])assert.throws(()=>S.total({9:q}),RangeError);});
test('rejects invalid type IDs',()=>{for(const id of [0,11,999,'9',1.5])assert.throws(()=>S.ruleFor(id),RangeError);});
test('repeated input replaces quantity, never double-awards',()=>{const s=S.sanitize(null,teams);S.setCount(s,'one',9,2);S.setCount(s,'one',9,2);assert.equal(S.total(s.teams.one),1998);});
test('team balances are isolated',()=>{const s=S.sanitize(null,teams);S.setCount(s,'one',9,2);assert.equal(S.total(s.teams.two),0);});
test('an invalid update is atomic',()=>{const s=S.sanitize(null,teams);const before=JSON.stringify(s);assert.throws(()=>S.setCount(s,'one',9,-1));assert.equal(JSON.stringify(s),before);});
test('unknown team cannot be created by an award',()=>assert.throws(()=>S.setCount(S.sanitize(null,teams),'bad',9,1),RangeError));
test('unapproved proposal cannot be activated by count input',()=>assert.throws(()=>S.setCount(S.sanitize(null,teams),'one',10,1),RangeError));
test('safe storage roundtrip preserves data',()=>{const s=S.sanitize(null,teams);S.setCount(s,'two',9,3);assert.equal(S.total(S.sanitize(JSON.parse(JSON.stringify(s)),teams).teams.two),2997);});
test('corrupt saved counts are discarded',()=>{const s=S.sanitize({version:1,teams:{one:{1:-1,2:'4',4:9,9:2}}},teams);assert.equal(S.total(s.teams.one),1998);});
test('unknown legacy schemas do not migrate or invent rewards',()=>assert.equal(S.total(S.sanitize({version:2,teams:{one:{9:99}}},teams).teams.one),0));
test('rules are immutable',()=>assert.throws(()=>{S.ruleFor(9).value=50000;},TypeError));
test('million-count boundary remains an exact safe integer',()=>assert.equal(S.total({9:1000000}),999000000));
