"use strict";
const assert=require("node:assert/strict");
const core=require("./hitster-personal-core.js");
const songs=["לו יהי","Take on Me","כוח הכבידה","כולם גנבים","One Last Time"].map(title=>({title,artist:""}));
assert.equal(core.validateSongs(songs),"");
assert.ok(core.validateSongs(songs.slice(0,4)));
assert.ok(core.validateSongs([...songs,songs[0]]));
assert.ok(core.validateSongs(songs.map((s,i)=>i===4?{title:""}:s)));
assert.ok(core.validateSongs(songs.map((s,i)=>i===4?{title:" take ON me "}:s)));
assert.equal(core.musicLink("https://open.spotify.com/playlist/example?si=abc","spotify"),"https://open.spotify.com/playlist/example?si=abc");
assert.equal(core.musicLink("https://music.apple.com/il/playlist/example/pl.example","apple"),"https://music.apple.com/il/playlist/example/pl.example");
for(const bad of ["javascript:alert(1)","https://open.spotify.com.evil.test/x","https://user:secret@open.spotify.com/x","http://open.spotify.com/x","https://music.apple.com/x"])assert.throws(()=>core.musicLink(bad,"spotify"));
const original={"team-1":0,"team-2":5};
assert.deepEqual(core.scoreChange(original,"team-1",-1),{"team-1":-1,"team-2":5});
assert.deepEqual(original,{"team-1":0,"team-2":5});
assert.throws(()=>core.scoreChange(original,"missing",1));
assert.throws(()=>core.scoreChange(original,"team-1",100));
assert.equal(core.catalogCard({trackId:1,trackName:"Unknown",artistName:"Artist",releaseDate:""}),null);
assert.equal(core.catalogCard({trackId:1,trackName:"Blocked",artistName:"Michael Jackson",releaseDate:"1982-01-01"}),null);
const candidate={trackId:123,trackName:"One Last Time",artistName:"Ariana Grande",releaseDate:"2014-08-22",previewUrl:"https://audio-ssl.itunes.apple.com/sample.m4a"};
assert.equal(core.matchSong({title:"One Last Time",artist:"Ariana Grande"},[candidate]),candidate);
assert.equal(core.matchSong({title:"One Last Time",artist:"Wrong Artist"},[candidate]),null);
assert.equal(core.catalogCard(candidate).yearBasis,"catalog-release");
console.log("Personal mode passed: exactly five unique songs, safe provider links, manager score changes, catalog identity and year validation.");
