/* TRA offline service worker. The file list is generated by Python. */
importScripts("./offline-catalog.js");

const CATALOG = globalThis.TRA_OFFLINE_CATALOG || { revision: "missing", files: [] };
const CACHE_PREFIX = "tra-offline-";
const CACHE = `${CACHE_PREFIX}${CATALOG.revision}`;
const STATUS_KEY = new URL("__tra_offline_status__", self.registration.scope).href;
const QUALITY_SRC = new URL("tra-quality.js", self.registration.scope).href;
const BOOTSTRAP_SRC = new URL("offline-bootstrap.js", self.registration.scope).href;
const FALLBACK_PAGE = new URL("offline.html", self.registration.scope).href;
const CORE = [...new Set((CATALOG.files || []).map((path) => new URL(path, self.registration.scope).href))]
  .filter((url) => new URL(url).origin === self.location.origin);

const injectSharedScripts = (html) => {
  let next = html;
  if (!next.includes("data-tra-offline-bootstrap")) {
    next = next.replace(/<\/body>/i, `<script src="${BOOTSTRAP_SRC}" data-tra-offline-bootstrap></script></body>`);
  }
  if (!next.includes("data-tra-quality")) {
    next = next.replace(/<\/body>/i, `<script src="${QUALITY_SRC}" data-tra-quality></script></body>`);
  }
  return next;
};

async function decorateNavigation(response) {
  const type = response.headers.get("content-type") || "";
  if (!type.includes("text/html")) return response;
  const headers = new Headers(response.headers);
  headers.delete("content-length");
  headers.delete("content-encoding");
  headers.delete("etag");
  return new Response(injectSharedScripts(await response.text()), {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

async function cacheAll() {
  const cache = await caches.open(CACHE);
  const results = await Promise.allSettled(CORE.map(async (url) => {
    const response = await fetch(new Request(url, { cache: "reload" }));
    if (!response.ok) throw new Error(`${response.status} ${url}`);
    await cache.put(url, response);
  }));
  const failed = results.filter((result) => result.status === "rejected").length;
  const status = { cached: CORE.length - failed, failed, total: CORE.length, revision: CATALOG.revision };
  await cache.put(STATUS_KEY, new Response(JSON.stringify(status), { headers: { "content-type": "application/json" } }));
  return status;
}

async function currentStatus() {
  const cache = await caches.open(CACHE);
  const stored = await cache.match(STATUS_KEY);
  if (stored) return stored.json();
  const cached = (await Promise.all(CORE.map((url) => cache.match(url)))).filter(Boolean).length;
  return { cached, failed: Math.max(0, CORE.length - cached), total: CORE.length, revision: CATALOG.revision };
}

async function postStatus(client) {
  if (client?.postMessage) client.postMessage({ type: "TRA_OFFLINE_STATUS", ...(await currentStatus()) });
}

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    await cacheAll();
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE).map((key) => caches.delete(key)));
    await self.clients.claim();
  })());
});

self.addEventListener("message", (event) => {
  if (event.data?.type === "TRA_CACHE_ALL") {
    event.waitUntil(cacheAll().then(() => postStatus(event.source)));
  } else if (event.data?.type === "TRA_OFFLINE_STATUS") {
    event.waitUntil(postStatus(event.source));
  }
});

async function networkFirst(request) {
  try {
    const response = await fetch(request);
    if (response?.ok) {
      const saved = request.mode === "navigate" ? await decorateNavigation(response.clone()) : response.clone();
      caches.open(CACHE).then((cache) => cache.put(request, saved)).catch(() => {});
    }
    return response;
  } catch {
    const cached = await caches.match(request, { ignoreSearch: false });
    if (cached) return request.mode === "navigate" ? decorateNavigation(cached) : cached;
    if (request.mode === "navigate") {
      const fallback = await caches.match(FALLBACK_PAGE);
      if (fallback) return decorateNavigation(fallback);
    }
    return Response.error();
  }
}

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;
  const url = new URL(event.request.url);
  if (url.origin === self.location.origin) event.respondWith(networkFirst(event.request));
});
