(function(){
'use strict';
const C=window.TRACore,$=id=>document.getElementById(id),KEY='tra.primate-lab.v1.state';
const uid=()=>window.crypto&&crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
const NAMES={chimp:'שִׁימְפַּנְזָה',gorilla:'גּוֹרִילָה',baboon:'בָּבּוּן'};
const SOURCES={chimp:'https://animals.sandiegozoo.org/animals/chimpanzee',gorilla:'https://animals.sandiegozoo.org/animals/gorilla',baboon:'https://animals.sandiegozoo.org/animals/hamadryas-baboon',tools:'https://janegoodall.org/news/chimpanzee-cultures-knowledge-passed-through-generations/'};
const FACTS={chimp:{title:'מַקֵּל קָטָן, רַעְיוֹן גָּדוֹל.',text:'שִׁימְפַּנְזִים בַּטֶּבַע מְשַׁנִּים מַקְלוֹת וּמִשְׁתַּמְּשִׁים בָּהֶם כִּכְלֵי עֲבוֹדָה. מָסוֹרוֹת שֶׁל שִׁמּוּשׁ בְּכֵלִים עֲשׂוּיוֹת לְהִשְׁתַּנּוֹת בֵּין קְבוּצוֹת.',source:SOURCES.tools,ability:'בַּמִּשְׂחָק: כִּוּוּן עוֹזֵר מְדֻיָּק וּתַחֲנוֹת גִּלּוּי כֵלִים.'},gorilla:{title:'גַּם לָנוּחַ זוֹ מְלָאכָה.',text:'גּוֹרִילוֹת בּוֹנוֹת קִנִּים מֵעָלִים, זְרָדִים וַעֲנָפִים לִמְנוּחָה. הַצְּעִירִים לוֹמְדִים גַּם מִמִּשְׂחָק וּמֵחִקּוּי.',source:SOURCES.gorilla,ability:'בַּמִּשְׂחָק: טְוַח הָאֲחִיזָה רָחָב יוֹתֵר וְסַלְחָנִי יוֹתֵר.'},baboon:{title:'לִהְיוֹת חֵלֶק מִקְּבוּצָה.',text:'אֵצֶל בָּבּוּנִים מִצְרִיִּים, טִפּוּחַ הֲדָדִי הוּא חֵלֶק חָשׁוּב מֵהַקְּשָׁרִים הַחֶבְרָתִיִּים. הַזָּנָב שֶׁלָּהֶם אֵינוֹ מְשַׁמֵּשׁ לְלִפְתִיתָה.',source:SOURCES.baboon,ability:'בַּמִּשְׂחָק: תְּצוּגַת מַסְלוּל אֲרֻכָּה יוֹתֵר לִפְנֵי הַשִּׁגּוּר.'}};
const QUIZZES={
chimp:[{q:'מָה יָכוֹל לַעֲזֹר לְשִׁימְפַּנְזָה לְהוֹצִיא טֶרְמִיטִים?',a:['מַקֵּל שֶׁהֻתְאַם לַמְּשִׂימָה','זָנָב לוֹפֵת','מַפְתֵּחַ מַתֶּכֶת'],correct:0,why:'שִׁימְפַּנְזִים יְכוֹלִים לְעַצֵּב מַקְלוֹת וּלְהִשְׁתַּמֵּשׁ בָּהֶם לְהוֹצָאַת טֶרְמִיטִים.',source:SOURCES.tools},{q:'לְשִׁימְפַּנְזָה יֵשׁ זָנָב?',a:['כֵּן, לְאֲחִיזָה בָּעֵץ','לֹא, הִיא קוֹף־אָדָם לְלֹא זָנָב','רַק בַלַּיְלָה'],correct:1,why:'שִׁימְפַּנְזִים הֵם קוֹפֵי־אָדָם. אֵין לָהֶם זָנָב.',source:SOURCES.chimp},{q:'הַאִם כָּל קְבוּצוֹת הַשִּׁימְפַּנְזִים מִשְׁתַּמְּשׁוֹת בְּאוֹתָם כֵּלִים?',a:['כֵּן, תָּמִיד','אֵין שִׁמּוּשׁ בְּכֵלִים','לֹא, יֵשׁ מָסוֹרוֹת שׁוֹנוֹת'],correct:2,why:'מָסוֹרוֹת שֶׁל שִׁמּוּשׁ בְּכֵלִים שׁוֹנוֹת בֵּין קְבוּצוֹת.',source:SOURCES.tools}],
gorilla:[{q:'מִמָּה גּוֹרִילָה בּוֹנָה קֵן לִמְנוּחָה?',a:['מֵאֲבָנִים וּמִבֵּטוֹן','מֵעָלִים, זְרָדִים וַעֲנָפִים','מִזְּכוּכִית'],correct:1,why:'קֵן מִצִּמְחִיָּה מְשַׁמֵּשׁ גּוֹרִילוֹת לִמְנוּחָה.',source:SOURCES.gorilla},{q:'מָה נָכוֹן לְגַבֵּי הַגּוֹרִילָה?',a:['הִיא קוֹף־אָדָם לְלֹא זָנָב','הִיא בַּעֲלַת זָנָב לוֹפֵת','הִיא סוּג שֶׁל בָּבּוּן'],correct:0,why:'גּוֹרִילוֹת וְשִׁימְפַּנְזִים נִמְנִים עִם קוֹפֵי־הָאָדָם, שֶׁאֵין לָהֶם זָנָב.',source:SOURCES.chimp},{q:'אֵיךְ גּוֹרִילוֹת צְעִירוֹת לוֹמְדוֹת גַּם מֵהַקְּבוּצָה?',a:['רַק מִסְּפָרִים','לְלֹא הִתְבּוֹנְנוּת','בְּחִקּוּי וּבְמִשְׂחָק'],correct:2,why:'חִקּוּי וּמִשְׂחָק הֵם חֵלֶק מִלְּמִידַת מְיֻמָּנֻיּוֹת אֵצֶל גּוֹרִילוֹת צְעִירוֹת.',source:SOURCES.gorilla}],
baboon:[{q:'מָה תּוֹרֵם לַקְּשָׁרִים אֵצֶל בָּבּוּנִים מִצְרִיִּים?',a:['טִפּוּחַ הֲדָדִי','הִמָּנְעוּת מִכָּל מַגָּע חֶבְרָתִי','בְּנִיַּת בָּתֵּי אֶבֶן'],correct:0,why:'טִפּוּחַ הֲדָדִי הוּא הִתְנַהֲגוּת חֶבְרָתִית חֲשׁוּבָה אֵצֶל בָּבּוּנִים מִצְרִיִּים.',source:SOURCES.baboon},{q:'הַאִם הַזָּנָב שֶׁל בָּבּוּן מִצְרִי לוֹפֵת עֲנָפִים?',a:['כֵּן, כְּמוֹ יָד נוֹסֶפֶת','לֹא, הוּא אֵינוֹ זָנָב לוֹפֵת','אֵין לוֹ זָנָב'],correct:1,why:'לְבָּבּוּן מִצְרִי יֵשׁ זָנָב, אֲבָל הוּא אֵינוֹ לוֹפֵת.',source:SOURCES.baboon},{q:'מָתַי בָּבּוּנִים מִצְרִיִּים פְּעִילִים בְּדֶרֶךְ כְּלָל?',a:['רַק בַּלַּיְלָה','רַק בַּחֹרֶף','בַּיּוֹם'],correct:2,why:'בָּבּוּנִים מִצְרִיִּים הֵם פְּעִילֵי יוֹם.',source:SOURCES.baboon}]
};
let state=C.newState(),savedRaw=null,damagedRaw=null,storageBroken=false,currentTab='journey',saveTimer,toastTimer,composing=false;
function today(){try{const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jerusalem',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const f=k=>p.find(x=>x.type===k).value;return f('year')+'-'+f('month')+'-'+f('day');}catch(e){return new Date().toISOString().slice(0,10);}}
function warn(text){$('storageWarning').textContent=text;$('storageWarning').hidden=false;$('saveState').textContent='לֹא נִשְׁמַר — נָחוּץ גִּבּוּי';}
try{savedRaw=localStorage.getItem(KEY);if(savedRaw)state=C.validateState(JSON.parse(savedRaw));}catch(e){storageBroken=true;damagedRaw=savedRaw;warn('הָאִחְסוּן חָסוּם אוֹ הַמֵּידָע שֶׁבּוֹ אֵינוֹ קָרִיא. הַמָּקוֹר לֹא יִדָּרֵס. שִׁנּוּיִים נִשְׁמָרִים בְּזִכְרוֹן הַלְּשׁוֹנִית בִּלְבַד; יַצֵּא גִּבּוּי.');}
function save(){clearTimeout(saveTimer);if(storageBroken){warn('הָאִחְסוּן אֵינוֹ זָמִין. יַצֵּא גִּבּוּי לִפְנֵי סְגִירַת הַלְּשׁוֹנִית.');return false;}try{const disk=localStorage.getItem(KEY);if(disk&&disk!==savedRaw){try{state=C.merge(state,JSON.parse(disk));}catch(e){damagedRaw=disk;storageBroken=true;warn('נִמְצָא מֵידָע לֹא קָרִיא. הוּא לֹא יִדָּרֵס; יֵשׁ לְיַצֵּא גִּבּוּי.');return false;}}const raw=JSON.stringify(state);localStorage.setItem(KEY,raw);savedRaw=raw;$('saveState').innerHTML='<i class="storage-ok"></i>נִשְׁמַר בַּדַּפְדְּפָן';return true;}catch(e){warn('הָאִחְסוּן חָסוּם אוֹ מָלֵא. הַשִּׁנּוּיִים כָּרֶגַע בְּזִכְרוֹן בִּלְבַד. יַצֵּא גִּבּוּי.');return false;}}
function queueSave(){clearTimeout(saveTimer);$('saveState').textContent='שׁוֹמֵר…';saveTimer=setTimeout(save,350);}
function toast(s){clearTimeout(toastTimer);$('toast').textContent=s;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3300);}
if(location.protocol==='file:'&&!storageBroken){$('storageWarning').hidden=false;$('storageWarning').textContent='זוֹ פְּתִיחָה שֶׁל קֹבֶץ מְקוֹמִי. הַשְּׁמִירָה תְּלוּיָה בַּדַּפְדְּפָן וּבְמִקּוּם הַקֹּבֶץ. שְׁמוֹר גִּבּוּיִים; לְשִׁמּוּשׁ קָבוּעַ הַפְעֵל אֶת הַשָּׁרָת הַמְּקוֹמִי שֶׁבַּחֲבִילָה.';}
$('originalText').textContent=C.ORIGINAL;$('archiveOriginal').textContent=C.ORIGINAL;$('sequence').value=state.draft;$('tempo').value=state.bpm;$('volume').value=Math.round(state.volume*100);$('noteDate').value=today();$('todayTag').textContent=today().split('-').reverse().join('.')+' · יִשְׂרָאֵל';
if(window.parent!==window)document.body.classList.add('embedded');
// Small original vector characters; only the baboon has a tail.
function ellipse(ctx,x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function avatar(ctx,x,y,r,species,angle=0){ctx.save();ctx.translate(x,y);ctx.rotate(angle);let fur=species==='gorilla'?'#485648':species==='baboon'?'#a4825e':'#71533c',face=species==='gorilla'?'#aab199':species==='baboon'?'#d9ba99':'#d9b68c';
 if(species==='baboon'){ctx.strokeStyle=fur;ctx.lineWidth=r*.22;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(r*.5,r*.5);ctx.bezierCurveTo(r*1.6,r*.3,r*1.7,-r*.55,r*1.25,-r*.62);ctx.stroke();}
 ellipse(ctx,0,r*.4,r*.66,r*.66,fur);ellipse(ctx,-r*.7,-r*.12,r*.3,r*.38,fur);ellipse(ctx,r*.7,-r*.12,r*.3,r*.38,fur);ellipse(ctx,-r*.7,-r*.12,r*.19,r*.24,face);ellipse(ctx,r*.7,-r*.12,r*.19,r*.24,face);ellipse(ctx,0,-r*.17,r*.73,r*.76,fur);ellipse(ctx,-r*.25,-r*.26,r*.3,r*.34,face);ellipse(ctx,r*.25,-r*.26,r*.3,r*.34,face);ellipse(ctx,0,r*.07,species==='baboon'?r*.37:r*.47,species==='baboon'?r*.55:r*.33,face);ellipse(ctx,-r*.23,-r*.26,r*.065,r*.09,'#21372d');ellipse(ctx,r*.23,-r*.26,r*.065,r*.09,'#21372d');ellipse(ctx,0,r*.09,r*.11,r*.075,'#544335');ctx.strokeStyle='#544335';ctx.lineWidth=r*.045;ctx.lineCap='round';ctx.beginPath();ctx.arc(0,r*.1,r*.23,.4,Math.PI-.4);ctx.stroke();if(species==='gorilla'){ctx.strokeStyle=fur;ctx.lineWidth=r*.12;ctx.beginPath();ctx.moveTo(-r*.43,-r*.47);ctx.lineTo(r*.43,-r*.47);ctx.stroke();}ctx.restore();}
document.querySelectorAll('[data-avatar]').forEach(c=>avatar(c.getContext('2d'),50,50,37,c.dataset.avatar));
function drawInstrument(){const ctx=$('instrument').getContext('2d');ctx.clearRect(0,0,500,240);ctx.strokeStyle='#acc096';ctx.lineWidth=1;for(let i=0;i<7;i++){ctx.beginPath();ctx.arc(255,137,35+i*17,Math.PI*.9,Math.PI*2.1);ctx.stroke();}ellipse(ctx,254,195,120,12,'#c4d2b4');ctx.fillStyle='#77543a';ctx.fillRect(121,164,245,17);ellipse(ctx,170,130,40,47,'#ac8052');ellipse(ctx,170,108,40,15,'#e0b56c');ctx.strokeStyle='#a27340';ctx.lineWidth=9;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(240,172);ctx.lineTo(270,63);ctx.lineTo(320,172);ctx.stroke();ctx.lineWidth=1.5;ctx.strokeStyle='#e0b56c';for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(270+i*5,69+i*11);ctx.lineTo(251+i*12,166);ctx.stroke();}ctx.strokeStyle='#789560';ctx.lineWidth=14;ctx.beginPath();ctx.moveTo(350,162);ctx.lineTo(355,72);ctx.stroke();ctx.lineWidth=4;ctx.strokeStyle='#d0dfa8';ctx.beginPath();ctx.moveTo(355,72);ctx.lineTo(381,61);ctx.stroke();avatar(ctx,70,128,34,'chimp');}
drawInstrument();
// Web Audio: one context, user gesture only, bounded look-ahead scheduling.
let audio=null,master=null,voices=new Set(),playback=null,audioTimer=null,epoch=0;
async function enableAudio(){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio){$('audioStatus').textContent='שֵׁמַע אֵינוֹ נִתְמָךְ בַּדַּפְדְּפָן. הָרֶצֶף וְהַמִּשְׂחָק עֲדַיִן זְמִינִים.';return false;}try{if(!audio){audio=new Audio();master=audio.createGain();master.gain.value=state.volume;const limiter=audio.createDynamicsCompressor();master.connect(limiter);limiter.connect(audio.destination);}if(audio.state==='suspended')await audio.resume();if(audio.state!=='running')throw Error('Not running');return true;}catch(e){$('audioStatus').textContent='הַדַּפְדְּפָן לֹא הִפְעִיל שֵׁמַע. לְחַץ שׁוּב עַל נְגִינָה וּבְדֹק אֶת הָעָצְמָה.';return false;}}
function sound(token,time,duration){if(!audio||!master||token.kind!=='tone')return;const osc=audio.createOscillator(),env=audio.createGain();osc.type=token.wave;osc.frequency.setValueAtTime(token.frequency,time);if(token.ch==='ב')osc.frequency.exponentialRampToValueAtTime(token.frequency*.65,time+.12);const dur=Math.max(.07,Math.min(duration,.65));env.gain.setValueAtTime(0,time);env.gain.linearRampToValueAtTime(.28,time+.012);env.gain.exponentialRampToValueAtTime(.001,time+dur);osc.connect(env);env.connect(master);osc.start(time);osc.stop(time+dur+.02);voices.add(osc);osc.onended=()=>{voices.delete(osc);osc.disconnect();env.disconnect();};}
function stopAudio(){epoch++;clearInterval(audioTimer);audioTimer=null;playback=null;voices.forEach(o=>{try{o.stop();}catch(e){}});voices.clear();document.querySelectorAll('.token.playing').forEach(el=>el.classList.remove('playing'));$('playSequence').disabled=false;}
function pump(){if(!playback||!audio)return;const p=playback,elapsed=audio.currentTime-p.start;while(p.next<p.events.length&&p.events[p.next].time<elapsed+.12){const e=p.events[p.next++];sound(e,p.start+e.time,e.duration*.85);}while(p.visible+1<p.events.length&&p.events[p.visible+1].time<=elapsed){p.visible++;const old=$('tokenList').querySelector('.playing');if(old)old.classList.remove('playing');const el=$('tokenList').children[p.visible];if(el)el.classList.add('playing');$('audioStatus').textContent='תָּו '+(p.visible+1)+' מִתּוֹךְ '+p.events.length+' · '+p.events[p.visible].label;}
 if(elapsed>p.end+.1){stopAudio();$('audioStatus').textContent='הָרֶצֶף נֻגַּן עַד הַתָּו הָאַחֲרוֹן.';}}
async function play(){stopAudio();const mine=epoch;if(!state.draft.length){toast('אֶפְשָׁר לִכְתֹּב גַּם אוֹת אַחַת.');return;}if(!await enableAudio()||mine!==epoch)return;const events=C.timeline(state.draft,state.bpm);playback={events,start:audio.currentTime+.07,next:0,visible:-1,end:events.length?events[events.length-1].time+events[events.length-1].duration:0};$('playSequence').disabled=true;audioTimer=setInterval(pump,30);pump();}
$('playSequence').onclick=play;$('stopSequence').onclick=()=>{stopAudio();$('audioStatus').textContent='הַנְּגִינָה נֶעֶצְרָה. הָרֶצֶף לֹא הִשְׁתַּנָּה.';};
document.querySelectorAll('[data-pad]').forEach(b=>b.onclick=async()=>{stopAudio();if(await enableAudio())sound(C.tokens(b.dataset.pad)[0],audio.currentTime+.01,.45);});
function renderTokens(){const tt=C.tokens(state.draft);$('tokenList').replaceChildren();const frag=document.createDocumentFragment();tt.forEach(t=>{const b=document.createElement('button');b.type='button';b.className='token '+t.kind;b.title=(t.index+1)+' · '+t.code;b.setAttribute('aria-label','תָּו '+(t.index+1)+': '+t.label+', '+t.code);const text=document.createElement('span');text.textContent=t.kind==='mark'?'◌'+t.ch:t.label;const small=document.createElement('small');small.textContent=String(t.index+1);b.append(text,small);b.onclick=async()=>{stopAudio();if(t.kind==='tone'&&await enableAudio())sound(t,audio.currentTime+.01,.35);else $('audioStatus').textContent=t.label+' — נִשְׁמַר כְּחֵלֶק מֵהָרֶצֶף.';};frag.append(b);});$('tokenList').append(frag);$('letterStats').innerHTML='<span><strong>'+tt.length+'</strong>תָּוִים</span><span><strong>'+tt.filter(t=>t.kind==='tone').length+'</strong>אוֹתִיּוֹת וּצְלִילִים</span><span><strong>'+tt.filter(t=>t.kind==='space').length+'</strong>רְוָחִים</span><span><strong>'+tt.filter(t=>['mark','punctuation'].includes(t.kind)).length+'</strong>סִמָּנִים</span>';$('codepoints').textContent=tt.map(t=>String(t.index+1).padStart(3,'0')+'  '+t.code+'  '+JSON.stringify(t.ch)).join('\n');$('tempoValue').textContent=state.bpm;$('volumeValue').textContent=Math.round(state.volume*100);}
$('sequence').addEventListener('compositionstart',()=>{composing=true;});$('sequence').addEventListener('compositionend',()=>{composing=false;draftChange();});
function draftChange(){if(composing)return;stopAudio();state.draft=$('sequence').value;renderTokens();queueSave();}
$('sequence').addEventListener('input',draftChange);$('tempo').oninput=()=>{stopAudio();state.bpm=Number($('tempo').value);$('tempoValue').textContent=state.bpm;queueSave();};$('volume').oninput=()=>{state.volume=Number($('volume').value)/100;if(master)master.gain.setTargetAtTime(state.volume,audio.currentTime,.025);$('volumeValue').textContent=$('volume').value;queueSave();};
function snapshot(raw){state.revisions.push({id:uid(),at:new Date().toISOString(),raw});return save();}
$('saveVersion').onclick=()=>{const ok=snapshot(state.draft);renderArchive();toast(ok?'הַגִּרְסָה נִשְׁמְרָה. הַמָּקוֹר לֹא הִשְׁתַּנָּה.':'הַגִּרְסָה בְּזִכְרוֹן בִּלְבַד. נָחוּץ גִּבּוּי.');};
$('restoreOriginal').onclick=()=>{stopAudio();if(state.draft!==C.ORIGINAL)snapshot(state.draft);state.draft=C.ORIGINAL;$('sequence').value=state.draft;save();renderTokens();toast('הַמָּקוֹר עַל שֻׁלְחַן הַנִּסּוּי. הַטְּיוּטָה הַקּוֹדֶמֶת נִשְׁמְרָה כְּגִרְסָה.');};
// Diary-adjacent notebook. Existing diary records and storage keys are never touched.
$('saveNote').onclick=()=>{const raw=$('noteText').value,date=$('noteDate').value;if(!raw.length){toast('כְּתֹב תְּצַפִּית קְטַנָּה לִפְנֵי הַשְּׁמִירָה.');return;}if(!/^\d{4}-\d{2}-\d{2}$/.test(date)){toast('יֵשׁ לִבְחֹר תַּאֲרִיךְ.');return;}state.notes.push({id:uid(),at:new Date().toISOString(),date,raw,species:state.species});const ok=save();$('noteText').value='';renderArchive();toast(ok?'הַתְּצַפִּית נוֹסְפָה לַמַּחְבֶּרֶת.':'הַתְּצַפִּית בְּזִכְרוֹן בִּלְבַד. נָחוּץ גִּבּוּי.');};
function recordHTML(list,items,versions){list.replaceChildren();if(!items.length){const d=document.createElement('div');d.className='empty';d.textContent=versions?'הַנִּסּוּי הָרִאשׁוֹן עוֹד לְפָנֶיךָ.':'הַמַּחְבֶּרֶת מַתְחִילָה בַּמִּלִּים שֶׁלְּךָ. אֵין תְּצַפִּיּוֹת מֻמְצָאוֹת.';list.append(d);return;}items.slice().reverse().forEach(r=>{const d=document.createElement('article');d.className='record';const small=document.createElement('small');small.textContent=(r.date||r.at.slice(0,10))+(r.species?' · '+NAMES[r.species]:' · '+C.tokens(r.raw).length+' תָּוִים');const p=document.createElement('p');p.dir='auto';p.textContent=r.raw;d.append(small,p);if(versions){const b=document.createElement('button');b.className='btn small-btn';b.textContent='פְּתִיחָה בַּמַּעְבָּדָה';b.onclick=()=>{if(state.draft!==r.raw)snapshot(state.draft);state.draft=r.raw;$('sequence').value=r.raw;save();renderTokens();setTab('lab');};d.append(b);}list.append(d);});}
function renderArchive(){recordHTML($('notesList'),state.notes,false);recordHTML($('versionsList'),state.revisions,true);}
function backup(){return{app:'TRA-Primate-Lab',schema:1,original:C.ORIGINAL,createdAt:new Date().toISOString(),state,recoveryRaw:damagedRaw};}
function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:'application/json;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
$('exportBackup').onclick=()=>download('TRA-Primate-Lab-'+today()+'.json',JSON.stringify(backup(),null,2));$('importBackup').onclick=()=>$('backupFile').click();
$('backupFile').onchange=async()=>{const f=$('backupFile').files[0];if(!f)return;try{if(f.size>8*1024*1024)throw Error('too large');const b=JSON.parse(await f.text());if(b.app!=='TRA-Primate-Lab'||b.schema!==1)throw Error('wrong app');const incoming=C.validateState(b.state);state=C.merge(state,incoming);const ok=save();renderArchive();renderTokens();toast(ok?'הַגִּבּוּי מֻזַּג. הַקַּיָּם נִשְׁמַר.':'הַמִּזּוּג בְּזִכְרוֹן בִּלְבַד. יֵשׁ לְיַצֵּא גִּבּוּי.');}catch(e){toast('הַגִּבּוּי אֵינוֹ תַּקִּין. לֹא שֻׁנָּה דָּבָר.');}$('backupFile').value='';};
// Sling game: fixed timestep; swept collision tests prevent skipped catches.
const canvas=$('game'),ctx=canvas.getContext('2d'),G=850,H=625;
let route=[],run=null,player={x:300,y:545,vx:0,vy:0},camera=0,mode='ready',started=false,paused=false,drag=null,assisted=null,lastFrame=0,acc=0,flightTime=0,shownQuiz=null,quizFocus=null,modeAfterPause='ready';
function getRun(){if(!state.runs[state.species])state.runs[state.species]={seed:today(),peg:0,shots:0,misses:0,complete:false};return state.runs[state.species];}
function configure(){run=getRun();route=C.nodes(run.seed+state.species);const n=route[run.peg];player={x:n.x,y:n.y,vx:0,vy:0};camera=n.y-500;mode=run.complete?'complete':'ready';drag=null;assisted=null;flightTime=0;$('journeyTitle').textContent='הַמַּסָּע שֶׁל הַ'+NAMES[state.species];const f=FACTS[state.species];$('factTitle').textContent=f.title;$('factText').textContent=f.text;$('factSource').href=f.source;$('abilityNote').textContent=f.ability;document.querySelectorAll('[data-species]').forEach(b=>{const active=b.dataset.species===state.species;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});$('startTitle').textContent=run.complete?'הַמַּסָּע הֻשְׁלַם. הַמַּעְבָּדָה מְחַכָּה.':run.peg?'נַמְשִׁיךְ מֵהַתַּחֲנָה שֶׁלְּךָ?':'יוֹצְאִים לְגַלּוֹת?';$('startButton').textContent=run.complete?'מַסָּע נוֹסָף ←':run.peg?'מַמְשִׁיכִים ←':'מַתְחִילִים לְשַׂחֵק ←';updateHUD();draw();}
function updateHUD(){$('pegCount').textContent=run.peg+' / 12';$('pegProgress').style.width=(run.peg/12*100)+'%';$('pauseButton').disabled=!started;$('launchButton').disabled=!started||paused||mode!=='ready';$('aimButton').disabled=!started||paused||mode!=='ready';}
function aimValues(){const angle=Number($('angle').value)*Math.PI/180,power=Number($('power').value)*9;return{vx:Math.sin(angle)*power,vy:-Math.cos(angle)*power};}
function syncSliders(){assisted=null;$('angleValue').textContent=$('angle').value+'°';$('powerValue').textContent=$('power').value+'%';draw();}
function helpAim(){if(!started||paused||mode!=='ready'||run.peg>=12)return;const a=C.aim(player,route[run.peg+1],G);assisted=a;$('angle').value=Math.round(Math.atan2(a.vx,-a.vy)*180/Math.PI);$('power').value=Math.round(Math.hypot(a.vx,a.vy)/9);$('angleValue').textContent=$('angle').value+'°';$('powerValue').textContent=$('power').value+'%';$('gameStatus').textContent='הַכִּוּוּן לַתַּחֲנָה הַבָּאָה מוּכָן. לְחַץ עַל שִׁגּוּר.';draw();}
function launch(v){if(!started||paused||mode!=='ready')return;player.vx=v.vx;player.vy=v.vy;mode='flight';flightTime=0;run.shots++;assisted=null;save();$('gameStatus').textContent='בַּדֶּרֶךְ לַתַּחֲנָה הַבָּאָה…';updateHUD();}
$('angle').oninput=syncSliders;$('power').oninput=syncSliders;$('aimButton').onclick=helpAim;$('launchButton').onclick=()=>launch(assisted||aimValues());
$('startButton').onclick=()=>{if(run.complete){state.notes.push({id:uid(),at:new Date().toISOString(),date:today(),species:state.species,raw:'סִכּוּם מִשְׂחָק: הֻשְׁלְמוּ 12 תַּחֲנוֹת בְּ־'+run.shots+' שִׁגּוּרִים.'});state.runs[state.species]={seed:today(),peg:0,shots:0,misses:0,complete:false};configure();}started=true;paused=false;$('startPanel').hidden=true;$('pauseButton').textContent='הַשְׁהָיָה';save();helpAim();updateHUD();};
function pause(){if(!started)return;paused=!paused;$('pauseButton').textContent=paused?'הֶמְשֵׁךְ':'הַשְׁהָיָה';$('gameStatus').textContent=paused?'הַמִּשְׂחָק מֻשְׁהֶה. אֵין לְאָן לְמַהֵר.':'חָזַרְנוּ לַמַּסָּע.';drag=null;save();updateHUD();}
$('pauseButton').onclick=pause;
document.querySelectorAll('[data-species]').forEach(b=>b.onclick=()=>{stopAudio();save();state.species=b.dataset.species;started=false;paused=false;$('startPanel').hidden=false;configure();save();});
function pointer(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width*600,y:(e.clientY-r.top)/r.height*H};}
canvas.addEventListener('pointerdown',e=>{if(!started||paused||mode!=='ready')return;const p=pointer(e);if(Math.hypot(p.x-player.x,p.y-(player.y-camera))>85)return;e.preventDefault();drag={x:p.x,y:p.y,id:e.pointerId};canvas.setPointerCapture(e.pointerId);});
canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const p=pointer(e);drag.x=p.x;drag.y=p.y;e.preventDefault();});
function dragVector(){let dx=player.x-drag.x,dy=(player.y-camera)-drag.y;const len=Math.hypot(dx,dy),f=Math.min(128,len)/(len||1);return{vx:dx*f*7,vy:dy*f*7};}
canvas.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const v=dragVector();drag=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);if(Math.hypot(v.vx,v.vy)>90)launch(v);});canvas.addEventListener('pointercancel',()=>{drag=null;});
function missed(){run.misses++;const n=route[run.peg];player={x:n.x,y:n.y,vx:0,vy:0};camera=n.y-500;mode='ready';flightTime=0;save();$('gameStatus').textContent='חוֹזְרִים לָאֲחִיזָה הָאַחֲרוֹנָה. אֵין אוֹבְדַן הִתְקַדְּמוּת.';helpAim();updateHUD();}
function catchPeg(index){run.peg=index;const n=route[index];player={x:n.x,y:n.y,vx:0,vy:0};mode=index===12?'complete':'ready';run.complete=index===12;save();updateHUD();$('gameStatus').textContent=index===12?'הִגַּעְתָּ לַצַּמֶּרֶת! הַכְּלִי וְהָרֶצֶף מְחַכִּים בַּמַּעְבָּדָה.':'תַּחֲנָה '+index+' נִשְׁמְרָה. עוֹד צַעַד שֶׁל גִּלּוּי.';if(index===12){showFinish();return;}if(index%3===0){const q=index/3-1;if(!state.learned.includes(state.species+'-'+q))showQuiz(q);}else helpAim();}
function physics(dt){if(mode!=='flight')return;flightTime+=dt;const old={x:player.x,y:player.y};player.x+=player.vx*dt;player.y+=player.vy*dt+.5*G*dt*dt;player.vy+=G*dt;const target=route[run.peg+1];if(target&&flightTime>.1&&C.segmentDistance(old.x,old.y,player.x,player.y,target.x,target.y)<(state.species==='gorilla'?39:state.species==='chimp'?29:26)){catchPeg(target.index);return;}if(player.x<25){player.x=25;player.vx=Math.abs(player.vx)*.7;}if(player.x>575){player.x=575;player.vx=-Math.abs(player.vx)*.7;}if(player.y>route[run.peg].y+220||flightTime>5)missed();}
let prevDialogFocus=null;
function showQuiz(idx){shownQuiz={index:idx,species:state.species};paused=true;prevDialogFocus=document.activeElement;const q=QUIZZES[state.species][idx];$('quizKicker').textContent='תַּחֲנַת גִּלּוּי · '+NAMES[state.species];$('quizTitle').textContent='רֶגַע קָטָן שֶׁל סַקְרָנוּת.';$('quizPrompt').textContent=q.q;$('quizFeedback').textContent='';$('quizContinue').hidden=true;$('quizOptions').replaceChildren();$('quizSource').href=q.source;$('quizSource').hidden=false;$('quizLater').hidden=false;$('quizContinue').textContent='מַמְשִׁיכִים בַּמַּסָּע ←';q.a.forEach((a,i)=>{const b=document.createElement('button');b.className='option';b.textContent=a;b.onclick=()=>{if(i!==q.correct){b.classList.add('wrong');$('quizFeedback').textContent='נְנַסֶּה שׁוּב. הַשְּׁאֵלָה הִיא חֵלֶק מֵהַלְּמִידָה.';return;}b.classList.add('correct');$('quizFeedback').textContent=q.why;const key=shownQuiz.species+'-'+idx;if(!state.learned.includes(key))state.learned.push(key);save();$('quizContinue').hidden=false;Array.from($('quizOptions').children).forEach(x=>x.disabled=true);$('quizContinue').focus();};$('quizOptions').append(b);});$('quizModal').hidden=false;$('quizModal').querySelector('.dialog').focus();updateHUD();}
function showFinish(){shownQuiz={finish:true};paused=true;prevDialogFocus=document.activeElement;$('quizKicker').textContent='12 תַּחֲנוֹת · מַסָּע שֶׁנִּשְׁמַר';$('quizTitle').textContent='עַכְשָׁו, נוֹתְנִים לָאוֹתִיּוֹת קוֹל.';$('quizPrompt').textContent='הַקּוֹף הִמְצִיא כְּלִי. אַתָּה עוֹזֵר הַמַּעְבָּדָה. הָרֶצֶף הַמְּקוֹרִי מְחַכֶּה לְךָ.';$('quizOptions').replaceChildren();$('quizFeedback').textContent=run.shots+' שִׁגּוּרִים · '+run.misses+' נִסְיוֹנוֹת חוֹזְרִים';$('quizSource').hidden=true;$('quizContinue').hidden=false;$('quizContinue').textContent='לַמַּעְבָּדָה ←';$('quizLater').hidden=true;$('quizModal').hidden=false;$('quizContinue').focus();}
function closeQuiz(){const finish=shownQuiz&&shownQuiz.finish;$('quizModal').hidden=true;shownQuiz=null;paused=false;helpAim();updateHUD();if(prevDialogFocus&&prevDialogFocus.isConnected)prevDialogFocus.focus();if(finish)setTab('lab');}
$('quizContinue').onclick=closeQuiz;$('quizLater').onclick=closeQuiz;
// Canvas scenery: generated vector art, no remote assets or copyrighted sprites.
function leaf(x,y,size,angle,color){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(0,0);ctx.quadraticCurveTo(size*.9,-size*.8,size*1.8,0);ctx.quadraticCurveTo(size*.8,size*.5,0,0);ctx.fill();ctx.restore();}
function scenery(){ctx.fillStyle='#dce6ce';ctx.fillRect(0,0,600,H);ctx.fillStyle='#e9edd7';ctx.beginPath();ctx.moveTo(210,0);ctx.bezierCurveTo(370,160,40,280,270,625);ctx.lineTo(420,625);ctx.bezierCurveTo(210,380,530,150,340,0);ctx.closePath();ctx.fill();ellipse(ctx,488,75,44,44,'#f3e5b6');ctx.strokeStyle='#9aaf85';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(41,-50);ctx.bezierCurveTo(79,160,10,390,51,700);ctx.stroke();ctx.beginPath();ctx.moveTo(562,-50);ctx.bezierCurveTo(514,230,590,470,536,700);ctx.stroke();for(let i=0;i<10;i++){const yy=(i*92-camera*.13)%810-80;leaf(45,yy,41,i%2?-.7:.8,'#afc298');leaf(556,yy+28,44,i%2?2.9:3.9,'#b4c59c');}for(let i=0;i<18;i++){const x=70+(i*83)%470,y=(i*97-camera*.08)%750-60;ellipse(ctx,x,y,2,2,'#c0d0ad');}}
function draw(){scenery();ctx.save();ctx.translate(0,-camera);ctx.setLineDash([3,10]);ctx.strokeStyle='#a0b589';ctx.lineWidth=2;ctx.beginPath();route.forEach((n,i)=>{if(i===0)ctx.moveTo(n.x,n.y);else ctx.lineTo(n.x,n.y);});ctx.stroke();ctx.setLineDash([]);route.forEach(n=>{if(n.y-camera < -70||n.y-camera>H+90)return;const next=n.index===run.peg+1,reached=n.index<=run.peg;ellipse(ctx,n.x,n.y+7,32,9,'#b8cba1');ellipse(ctx,n.x,n.y,next?29:24,next?29:24,reached?'#608458':next?'#e7b866':'#f4f4e2');ctx.strokeStyle=next?'#bb883d':'#91aa7e';ctx.lineWidth=2;ctx.beginPath();ctx.arc(n.x,n.y,next?29:24,0,Math.PI*2);ctx.stroke();ctx.fillStyle=reached?'#f1f2df':'#58704b';ctx.font='15px Arial';ctx.textAlign='center';ctx.textBaseline='middle';const letter=n.index===0?'•':n.index===12?'✦':n.index%3===0?['ב','נ','ה'][n.index/3-1]:String(n.index);ctx.fillText(letter,n.x,n.y+1);if(next){ctx.font='11px Arial';ctx.fillStyle='#44663c';ctx.fillText('הַתַּחֲנָה הַבָּאָה',n.x,n.y-45);}});
 if(started&&!paused&&mode==='ready'){const v=drag?dragVector():(assisted||aimValues());const count=state.species==='baboon'?33:22;for(let i=1;i<=count;i++){const t=i*.045,x=player.x+v.vx*t,y=player.y+v.vy*t+.5*G*t*t;if(x<10||x>590)break;ellipse(ctx,x,y,2.3,2.3,i%3===0?'#af7933':'#769763');}if(drag){ctx.strokeStyle='#6a6245';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(player.x-16,player.y+8);ctx.lineTo(drag.x,drag.y+camera);ctx.lineTo(player.x+16,player.y+8);ctx.stroke();}}
 avatar(ctx,player.x,player.y-20,28,state.species,mode==='flight'?Math.atan2(player.vx,700)*.4:0);ctx.restore();if(paused&&$('quizModal').hidden){ctx.fillStyle='#203d3466';ctx.fillRect(0,0,600,H);ctx.fillStyle='#fff8e8';ctx.font='26px Arial';ctx.textAlign='center';ctx.fillText('רֶגַע שֶׁל הַפְסָקָה',300,300);}}
function frame(now){const delta=Math.min((now-lastFrame)/1000||0, .05);lastFrame=now;if(currentTab==='journey'&&!document.hidden){if(started&&!paused){acc+=delta;while(acc>=1/120){physics(1/120);acc-=1/120;}}const target=route[run.peg].y-500;if(mode!=='flight')camera+=(target-camera)*Math.min(1,delta*9);draw();}requestAnimationFrame(frame);}
function setTab(tab){if(!['journey','lab','archive'].includes(tab))tab='journey';if(tab!=='lab')stopAudio();if(currentTab==='journey'&&tab!=='journey'){drag=null;if(mode==='flight'){const n=route[run.peg];player={x:n.x,y:n.y,vx:0,vy:0};mode='ready';}save();}currentTab=tab;document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==tab);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='archive')renderArchive();if(tab==='lab')renderTokens();updateHUD();}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
document.addEventListener('keydown',e=>{if(!$('quizModal').hidden){if(e.key==='Escape'){e.preventDefault();closeQuiz();return;}if(e.key==='Tab'){const focusables=Array.from($('quizModal').querySelectorAll('button,a[href]')).filter(x=>!x.hidden&&!x.disabled);const first=focusables[0],last=focusables[focusables.length-1];if(e.shiftKey&&(document.activeElement===first||!focusables.includes(document.activeElement))){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}if(/INPUT|TEXTAREA|SELECT|BUTTON|A/.test(e.target.tagName))return;if(currentTab!=='journey'||!started)return;if(e.key===' '){e.preventDefault();launch(assisted||aimValues());}if(e.key==='Escape'){pause();}if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();$('angle').value=C.clamp(Number($('angle').value)+(e.key==='ArrowLeft'?-3:3),-65,65);syncSliders();}if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();$('power').value=C.clamp(Number($('power').value)+(e.key==='ArrowUp'?3:-3),35,100);syncSliders();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopAudio();save();if(started&&!paused)pause();}});window.addEventListener('pagehide',()=>{stopAudio();save();});window.addEventListener('beforeunload',()=>save());window.addEventListener('message',e=>{if(e.source===window.parent&&e.data&&e.data.type==='tra-primate-hide'){stopAudio();save();if(started&&!paused)pause();}});
// Inspection hooks are read-only snapshots, useful for automated QA and export review.
window.TRAPrimate={original:C.ORIGINAL,tokens:C.tokens,timeline:C.timeline,backup:()=>JSON.parse(JSON.stringify(backup())),inspect:()=>({species:state.species,mode,started,paused,peg:run.peg,shots:run.shots,misses:run.misses,player:{...player},camera,route:route.map(n=>({...n})),audioState:audio?audio.state:null,playing:!!playback})};
configure();renderTokens();renderArchive();save();requestAnimationFrame(frame);
})();
